AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'config/**/*'
    - 'frontend/**/*'
    - 'Gemfile'

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Layout/IndentArray:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false
