apiVersion: apps/v1
kind: Deployment
metadata:
  name: balldontlie
  labels:
    app: balldontlie
spec:
  replicas: 2
  selector:
    matchLabels:
      app: balldontlie
  template:
    metadata:
      labels:
        app: balldontlie
    spec:
      containers:
      - name: balldontlie-api
        image: gcr.io/balldontlie/api:0.1
        ports:
        - name: http-server
          containerPort: 3000
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: database
          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: rails_secret
