apiVersion: v1
kind: Service
metadata:
  name: balldontlie
  labels:
    app: balldontlie
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http-server
  selector:
    app: balldontlie-api
