apiVersion: v1
kind: Service
metadata:
  name: balldontlie-client
  labels:
    app: balldontlie
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: http-server
  selector:
    app: balldontlie-client
